"""add salons and phase-1 model updates

Revision ID: f7ad2ddb6a36
Revises: ebc12f99c799
Create Date: 2026-09-18 14:29:35.577808

NOTE (Agent 5, minimal hand-edit): autogenerate emitted
``create_foreign_key(None, ...)`` inside ``batch_alter_table``. SQLite batch
mode recreates the table and requires NAMED constraints, so the three FKs
were given deterministic names (``fk_<table>_<col>_<referred>``) in both
``upgrade`` and ``downgrade``. No other statements were touched.
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f7ad2ddb6a36'
down_revision: Union[str, None] = 'ebc12f99c799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salons',
    sa.Column('salon_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('salon_id')
    )
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_barbers_salon_id'), ['salon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_barbers_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_barbers_salon_id_salons', 'salons', ['salon_id'], ['salon_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_barbers_user_id_users', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_services_salon_id'), ['salon_id'], unique=False)
        batch_op.create_foreign_key('fk_services_salon_id_salons', 'salons', ['salon_id'], ['salon_id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('fk_services_salon_id_salons', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_services_salon_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('salon_id')

    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_barbers_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_barbers_salon_id_salons', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_barbers_user_id'))
        batch_op.drop_index(batch_op.f('ix_barbers_salon_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('salon_id')
        batch_op.drop_column('user_id')

    op.drop_table('salons')
    # ### end Alembic commands ###
